import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'introduction',
    {
      type: 'category',
      label: 'Recipe catalog',
      link: {
        type: 'generated-index',
        title: 'Recipe catalog',
        description: 'A list of all OpenRewrite recipes.',
        slug: '/recipes',
        keywords: ['references'],
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'recipes'
        }
      ]
    },
  ],
};

export default sidebars;
